spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.111.95:3306/baijiajie?useUnicode=true&characterEncoding=UTF-8
    username: myuser
    password: mypassword
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true